import { useEffect, useState, type ReactNode } from 'react'
import './App.css'

type Movie = { movie_id: number; title: string; genres: string[]; average_rating?: number; rating_count?: number; weighted_rating?: number; predicted_rating?: number }
type Profile = { user_id: number; rating_count: number; average_rating: number; favorite_genres: string[] }
type HistoryItem = Movie & { rating: number }
type ColdRating = { movie_id: number; rating: number }
type NewUserProfile = { type: 'new'; genres: string[]; ratings: ColdRating[] }
type ColdRecommendation = Movie & { score: number; reason: string }
type View = 'home' | 'for-you' | 'popular' | 'top-rated' | 'genres' | 'genre' | 'movie' | 'profile' | 'performance' | 'about' | 'search'

const API_BASE =
  import.meta.env.VITE_API_URL ??
  (import.meta.env.PROD
    ? 'https://cinematch-backend-73w3.onrender.com'
    : 'http://localhost:8000')
const USERS = ['1', '2', '42', '100', '101', '200', '300', '400', '500', '600', '610']
const CANONICAL_GENRES = ['Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
const GENRE_ICONS: Record<string, string> = { Action: '💥', Comedy: '😊', Drama: '🎭', Horror: '💀', Romance: '❤️', 'Sci-Fi': '🚀', Thriller: '🗡️', Fantasy: '🧚', Adventure: '✈️', Animation: '🤖', "Children's": '🎈', Children: '🎈', Crime: '🕵️', Documentary: '🎬', Musical: '🎵', Mystery: '🔍', War: '⚔️', Western: '🤠' }
const POSTERS = ['linear-gradient(160deg,#1a1035,#3d1a6e)', 'linear-gradient(160deg,#0f172a,#1e3a5f)', 'linear-gradient(160deg,#1a0a00,#7c3d00)', 'linear-gradient(160deg,#0d1f12,#1a5c2e)', 'linear-gradient(160deg,#1a0020,#6b0f80)', 'linear-gradient(160deg,#001220,#005580)']

async function api<T>(path: string): Promise<T> { const response = await fetch(`${API_BASE}${path}`); if (!response.ok) throw new Error(`${response.status}`); return response.json() as Promise<T> }
async function postApi<T>(path: string, body: unknown): Promise<T> { const response = await fetch(`${API_BASE}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(`${response.status}`); return response.json() as Promise<T> }
function displayTitle(text: string) { return text.replace(/\s*\(\d{4}\)\s*$/, '').replace(/^(The|A|An),\s+/i, (_, article) => `${text.split(',')[1]?.trim() ?? ''} ${article}`.trim()) }
function Rating({ value }: { value?: number }) { return <span className="movie-rating"><span className="star-icon">★</span>{value == null ? '—' : value.toFixed(2)}</span> }

function MovieCard({ movie, index, onOpen }: { movie: Movie; index: number; onOpen: (movie: Movie) => void }) { const rating = movie.predicted_rating ?? movie.average_rating; return <button className="movie-card" type="button" onClick={() => onOpen(movie)}><div className="movie-poster" style={{ background: POSTERS[index % POSTERS.length] }}><span className="rank-badge">{index + 1}</span><span className="poster-title">{displayTitle(movie.title).slice(0, 28)}</span></div><div className="movie-card-info"><div className="movie-title">{displayTitle(movie.title)}</div><div className="movie-genres">{movie.genres?.slice(0, 3).join(', ')}</div><Rating value={rating} /><span className="rating-label">{movie.predicted_rating != null ? 'Predicted' : 'Average'}</span></div></button> }
function MovieList({ movies, onOpen }: { movies: Movie[]; onOpen: (movie: Movie) => void }) { return <div className="movie-list">{movies.length === 0 ? <div className="empty-state">No matching movies found.</div> : movies.map((movie, index) => <button className="movie-list-item" type="button" key={movie.movie_id} onClick={() => onOpen(movie)}><span className="list-rank">{index + 1}</span><div className="list-poster-mini" style={{ background: POSTERS[index % POSTERS.length] }}>{displayTitle(movie.title).charAt(0)}</div><div className="list-info"><div className="title">{displayTitle(movie.title)}</div><div className="genres">{movie.genres?.slice(0, 3).join(', ')}</div></div><Rating value={movie.weighted_rating ?? movie.average_rating} /></button>)}</div> }
function GenreGrid({ genres, onOpen }: { genres: string[]; onOpen: (genre: string) => void }) { return <div className="genre-grid">{genres.map(genre => <button type="button" className="genre-chip" key={genre} onClick={() => onOpen(genre)}><span className="genre-emoji">{GENRE_ICONS[genre] ?? '•'}</span>{genre}</button>)}</div> }
function MovieDetails({ movie, onBack }: { movie: Movie; onBack: () => void }) { return <section className="panel detail-panel"><button type="button" className="back-button" onClick={onBack}>← Back</button><div className="detail-layout"><div className="detail-poster" style={{ background: POSTERS[0] }}>🎞️</div><div><span className="eyebrow">MOVIE DETAILS</span><h2>{displayTitle(movie.title)}</h2><div className="detail-genres">{movie.genres.join(' · ')}</div><Rating value={movie.average_rating ?? movie.predicted_rating} /><dl><div><dt>Rating count</dt><dd>{movie.rating_count ?? '—'}</dd></div><div><dt>MovieLens ID</dt><dd>{movie.movie_id}</dd></div></dl></div></div></section> }
function Performance({ metrics }: { metrics: { models: { name: string; rmse: number }[]; precision_at_5: number; precision_at_10: number; best_model: string } | null }) { return metrics ? <><div className="model-table"><div className="model-row-header"><span>Model</span><span>RMSE ↓</span></div>{metrics.models.map(model => <div className={model.name === metrics.best_model ? 'model-row best' : 'model-row'} key={model.name}><span>{model.name}</span><strong>{model.rmse.toFixed(4)}</strong></div>)}</div><div className="precision-grid"><div className="precision-box pink"><span>Precision@5</span><strong>{(metrics.precision_at_5 * 100).toFixed(2)}%</strong></div><div className="precision-box purple"><span>Precision@10</span><strong>{(metrics.precision_at_10 * 100).toFixed(2)}%</strong></div></div></> : <div className="empty-state">Loading model metrics...</div> }

function NewUserOnboarding({ onComplete, onExisting }: { onComplete: (profile: NewUserProfile) => void; onExisting: () => void }) {
  const [step, setStep] = useState(1); const [selectedGenres, setSelectedGenres] = useState<string[]>([]); const [movies, setMovies] = useState<Movie[]>([]); const [ratings, setRatings] = useState<ColdRating[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const toggleGenre = (genre: string) => setSelectedGenres(current => current.includes(genre) ? current.filter(item => item !== genre) : current.length < 8 ? [...current, genre] : current)
  const loadMovies = async () => { setLoading(true); setError(''); try { const results = await Promise.all(selectedGenres.map(genre => api<{ movies: Movie[] }>(`/api/movies/genre/${encodeURIComponent(genre === "Children's" ? 'Children' : genre)}?limit=6`))); const unique = new Map<number, Movie>(); results.flatMap(result => result.movies).forEach(movie => unique.set(movie.movie_id, movie)); setMovies([...unique.values()].slice(0, 16)); setStep(2) } catch { setError('CineMatch recommendations are temporarily unavailable. Try again.'); } finally { setLoading(false) } }
  const setRating = (movieId: number, rating: number) => setRatings(current => [...current.filter(item => item.movie_id !== movieId), { movie_id: movieId, rating }])
  const finish = async () => { if (ratings.length < 5) { setError('Please rate at least 5 movies so CineMatch can understand your preferences.'); return }; setLoading(true); setError(''); try { onComplete({ type: 'new', genres: selectedGenres, ratings }) } catch { setError('CineMatch recommendations are temporarily unavailable. Try again.') } finally { setLoading(false) } }
  return <div className="welcome-screen"><div className="welcome-panel"><div className="brand-icon">🍿</div><span className="eyebrow">CINEMATCH / GET STARTED</span>{step === 1 ? <><h1>What kind of movies do you enjoy?</h1><p>Select 3 to 8 genres to shape your first recommendations.</p><div className="onboarding-genres">{CANONICAL_GENRES.map(genre => <button type="button" key={genre} className={selectedGenres.includes(genre) ? 'genre-chip selected' : 'genre-chip'} onClick={() => toggleGenre(genre)}><span className="genre-emoji">{GENRE_ICONS[genre] ?? '•'}</span>{genre}</button>)}</div><div className="onboarding-actions"><button type="button" className="secondary-button" onClick={onExisting}>Use Existing User</button><button type="button" className="hero-cta" disabled={selectedGenres.length < 3 || loading} onClick={() => void loadMovies()}>{loading ? 'Loading movies...' : 'Continue →'}</button></div></> : <><span className="step-label">STEP 2 OF 2</span><h1>Rate a few movies you know.</h1><p>Rate at least 5 movies. Skip anything unfamiliar.</p><div className="rating-onboarding-grid">{movies.map(movie => <div className="rating-onboarding-card" key={movie.movie_id}><div className="list-poster-mini" style={{ background: POSTERS[movie.movie_id % POSTERS.length] }}>{displayTitle(movie.title).charAt(0)}</div><strong>{displayTitle(movie.title)}</strong><span>{movie.genres.slice(0, 3).join(' · ')}</span><div className="star-rating">{[1, 2, 3, 4, 5].map(value => <button type="button" aria-label={`Rate ${value}`} className={ratings.find(item => item.movie_id === movie.movie_id)?.rating === value ? 'rated' : ''} key={value} onClick={() => setRating(movie.movie_id, value)}>★</button>)}</div></div>)}</div><div className="onboarding-actions"><button type="button" className="secondary-button" onClick={() => setStep(1)}>← Genres</button><button type="button" className="hero-cta" disabled={loading} onClick={() => void finish()}>{loading ? 'Finding movies...' : `Get recommendations (${ratings.length}/5)`}</button></div></>}{error && <div className="onboarding-error">{error}<button type="button" onClick={() => setError('')}>Dismiss</button></div>}<button type="button" className="existing-link" onClick={onExisting}>Already have a MovieLens User ID? Use Existing User</button></div></div>
}

export default function App() {
  const [view, setView] = useState<View>('home'); const [selectedUser, setSelectedUser] = useState('101'); const [selectedGenre, setSelectedGenre] = useState('Action'); const [selectedMovie, setSelectedMovie] = useState<Movie | null>(null)
  const [entryMode, setEntryMode] = useState<'new' | 'existing' | null>(() => localStorage.getItem('cinematch-user-mode') as 'new' | 'existing' | null); const [newUserProfile, setNewUserProfile] = useState<NewUserProfile | null>(() => { const saved = localStorage.getItem('cinematch-new-user'); return saved ? JSON.parse(saved) as NewUserProfile : null }); const [, setColdRecommendations] = useState<ColdRecommendation[]>([])
  const [genres, setGenres] = useState<string[]>([]); const [popular, setPopular] = useState<Movie[]>([]); const [topRated, setTopRated] = useState<Movie[]>([]); const [recommendations, setRecommendations] = useState<Movie[]>([]); const [recLoading, setRecLoading] = useState(true); const [genreMovies, setGenreMovies] = useState<Movie[]>([]); const [genreRecommendations, setGenreRecommendations] = useState<Movie[]>([]); const [profile, setProfile] = useState<Profile | null>(null); const [history, setHistory] = useState<HistoryItem[]>([]); const [search, setSearch] = useState(''); const [searchResults, setSearchResults] = useState<Movie[]>([]); const [metrics, setMetrics] = useState<{ models: { name: string; rmse: number }[]; precision_at_5: number; precision_at_10: number; best_model: string } | null>(null); const [error, setError] = useState(''); const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const open = (next: View) => { setView(next); window.scrollTo({ top: 0, behavior: 'smooth' }); setError('') }; const openMovie = (movie: Movie) => { setSelectedMovie(movie); open('movie') }; const changeUser = (user: string) => { setSelectedUser(user); setProfile(null); setEntryMode('existing'); localStorage.setItem('cinematch-user-mode', 'existing'); open('for-you') }; const chooseExisting = () => { setEntryMode('existing'); localStorage.setItem('cinematch-user-mode', 'existing') }; const completeOnboarding = (profileData: NewUserProfile) => { localStorage.setItem('cinematch-new-user', JSON.stringify(profileData)); localStorage.setItem('cinematch-user-mode', 'new'); setNewUserProfile(profileData); setEntryMode('new'); setView('home') }
  useEffect(() => { void Promise.all([api<string[]>('/api/genres'), api<{ movies: Movie[] }>('/api/movies/popular?limit=10'), api<{ movies: Movie[] }>('/api/movies/top-rated?limit=10')]).then(([g, p, t]) => { setGenres(CANONICAL_GENRES.filter(genre => g.includes(genre === "Children's" ? 'Children' : genre))); setPopular(p.movies); setTopRated(t.movies) }).catch(() => setError('The backend is offline. Start FastAPI on port 8000 to load live data.')) }, [])
  useEffect(() => { if (entryMode !== 'existing') return; setRecLoading(true); void api<{ recommendations: Movie[] }>(`/api/recommendations/${selectedUser}?limit=5`).then(data => setRecommendations(data.recommendations)).catch(() => setRecommendations([])).finally(() => setRecLoading(false)) }, [entryMode, selectedUser])
  useEffect(() => { if (entryMode !== 'new' || !newUserProfile) return; setRecLoading(true); void postApi<{ recommendations: ColdRecommendation[] }>('/api/recommendations/cold-start', { ...newUserProfile, limit: 5 }).then(data => { setColdRecommendations(data.recommendations); setRecommendations(data.recommendations) }).catch(() => setError('CineMatch recommendations are temporarily unavailable. Try Again.')).finally(() => setRecLoading(false)) }, [entryMode, newUserProfile])
  useEffect(() => { void api<Profile>(`/api/users/${selectedUser}`).then(setProfile).catch(() => setProfile(null)); void api<{ ratings: HistoryItem[] }>(`/api/users/${selectedUser}/history`).then(data => setHistory(data.ratings)).catch(() => setHistory([])) }, [selectedUser])
  useEffect(() => { if (view !== 'genre') return; const backendGenre = selectedGenre === "Children's" ? 'Children' : selectedGenre; void Promise.all([api<{ movies: Movie[] }>(`/api/movies/genre/${encodeURIComponent(backendGenre)}?limit=20`), api<{ recommendations: Movie[] }>(`/api/recommendations/${selectedUser}/genre/${encodeURIComponent(backendGenre)}?limit=5`)]).then(([movies, recommendationsForGenre]) => { setGenreMovies(movies.movies); setGenreRecommendations(recommendationsForGenre.recommendations) }).catch(() => { setGenreMovies([]); setGenreRecommendations([]) }) }, [view, selectedGenre, selectedUser])
  useEffect(() => { if (view !== 'performance') return; void api<typeof metrics>('/api/analytics/model-performance').then(setMetrics).catch(() => setMetrics(null)) }, [view])
  useEffect(() => { if (!search.trim()) { setSearchResults([]); return }; const timer = window.setTimeout(() => { void api<{ movies: Movie[] }>(`/api/movies/search?q=${encodeURIComponent(search)}&limit=20`).then(data => setSearchResults(data.movies)).catch(() => setSearchResults([])) }, 250); return () => window.clearTimeout(timer) }, [search])
  const nav = (label: string, target: View, icon: string) => <button type="button" className={view === target ? 'nav-button active' : 'nav-button'} onClick={() => { open(target); setMobileMenuOpen(false) }}><span>{icon}</span>{label}</button>; const section = (heading: string, sub: string, children: ReactNode) => <section className="panel page-section"><div className="panel-header"><div className="panel-title"><h3>{heading}</h3><span className="subtitle">{sub}</span></div></div>{children}</section>; const chooseGenre = (genre: string) => { setSelectedGenre(genre); open('genre'); setMobileMenuOpen(false) }
  let content: ReactNode
  if (view === 'home') content = <><div className="hero-banner"><div className="hero-content"><h2>Find your next favorite film.</h2><p>Personalized discovery powered by MovieLens ratings and SVD.</p><button className="hero-cta" type="button" onClick={() => open('for-you')}>Explore your matches →</button></div><div className="hero-visual">🎬</div></div>{section('For You', `Top recommendations for User ${selectedUser}`, recLoading ? <div className="loading-state">Loading SVD recommendations...</div> : <div className="movie-cards-row">{recommendations.map((movie, i) => <MovieCard key={movie.movie_id} movie={movie} index={i} onOpen={openMovie} />)}</div>)}<div className="bottom-grid">{section('Popular Movies', 'Weighted by rating volume', <><MovieList movies={popular.slice(0, 5)} onOpen={openMovie} /><button className="view-all-link" type="button" onClick={() => open('popular')}>View all</button></>)}{section('Top Rated', 'Highest average ratings', <><MovieList movies={topRated.slice(0, 5)} onOpen={openMovie} /><button className="view-all-link" type="button" onClick={() => open('top-rated')}>View all</button></>)}{section('Genres', 'Browse the catalog', <GenreGrid genres={genres.slice(0, 10)} onOpen={chooseGenre} />)}</div></>
  if (view === 'for-you') content = section(`For User ${selectedUser}`, 'SVD personalized recommendations', <><select className="user-id-select" value={selectedUser} onChange={e => changeUser(e.target.value)}>{USERS.map(user => <option key={user} value={user}>MovieLens User {user}</option>)}</select>{recLoading ? <div className="loading-state">Loading SVD recommendations...</div> : <div className="movie-cards-row">{recommendations.map((movie, i) => <MovieCard key={movie.movie_id} movie={movie} index={i} onOpen={openMovie} />)}</div>}</>)
  if (view === 'popular') content = section('Popular Movies', 'Most popular movies from MovieLens', <MovieList movies={popular} onOpen={openMovie} />); if (view === 'top-rated') content = section('Top Rated', 'Highest average rating with a meaningful history', <MovieList movies={topRated} onOpen={openMovie} />); if (view === 'genres') content = section('Genres', 'Choose a genre to explore', <GenreGrid genres={genres} onOpen={chooseGenre} />)
  if (view === 'genre') content = <>{section(`${selectedGenre} Movies`, 'Movies classified in this MovieLens genre', <MovieList movies={genreMovies} onOpen={openMovie} />)}{section(`User ${selectedUser} + ${selectedGenre}`, 'Top 5 SVD predictions within this genre', <><select className="user-id-select" value={selectedUser} onChange={e => setSelectedUser(e.target.value)}>{USERS.map(user => <option key={user} value={user}>User {user}</option>)}</select><div className="movie-cards-row">{genreRecommendations.map((movie, i) => <MovieCard key={movie.movie_id} movie={movie} index={i} onOpen={openMovie} />)}</div></>)}</>
  if (view === 'search') content = section(`Search results for “${search}”`, `${searchResults.length} matching movies`, <MovieList movies={searchResults} onOpen={openMovie} />); if (view === 'movie' && selectedMovie) content = <MovieDetails movie={selectedMovie} onBack={() => open('home')} />
  if (view === 'profile') content = section(`User ${selectedUser} Profile`, 'Your MovieLens activity', <><div className="stats-row"><div><strong>{profile?.rating_count ?? '—'}</strong><span>Ratings</span></div><div><strong>{profile?.average_rating.toFixed(2) ?? '—'}</strong><span>Average rating</span></div></div><h4>Rating history</h4><MovieList movies={history} onOpen={openMovie} /></>); if (view === 'performance') content = section('Model Performance', 'Evaluation on the MovieLens dataset', <Performance metrics={metrics} />); if (view === 'about') content = section('About CineMatch', 'From raw ratings to useful recommendations', <div className="about-copy"><p>MovieLens → EDA → Utility Matrix → Collaborative Filtering → SVD → Recommendations</p><p>CineMatch analyzes rating behavior, learns latent user and movie preferences, and ranks unseen movies with matrix factorization.</p></div>)
  if (!entryMode) return <NewUserOnboarding onComplete={completeOnboarding} onExisting={chooseExisting} />
  return <div className="app-shell"><button type="button" className="mobile-menu-button" aria-label="Open navigation" onClick={() => setMobileMenuOpen(true)}>☰</button>{mobileMenuOpen && <button type="button" className="mobile-menu-overlay" aria-label="Close navigation" onClick={() => setMobileMenuOpen(false)} />}<aside className={mobileMenuOpen ? 'sidebar mobile-open' : 'sidebar'}><div className="sidebar-brand"><div className="brand-icon">🍿</div><div className="brand-text">Cine<span>Match</span></div></div><span className="nav-section-label">MAIN</span>{nav('Home', 'home', '🏠')}{nav('For You', 'for-you', '🤖')}<span className="nav-section-label">DISCOVER</span>{nav('Popular Movies', 'popular', '🔥')}{nav('Top Rated', 'top-rated', '⭐')}{nav('Genres', 'genres', '🎭')}<span className="nav-section-label">ANALYTICS</span>{nav('Model Performance', 'performance', '📊')}{nav('About', 'about', 'ℹ️')}</aside><div className="main-area"><header className="topbar"><div className="topbar-search"><input value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === 'Enter' && open('search')} placeholder="Search movies..." autoComplete="off" /><span className="search-icon">🔍</span>{search && searchResults.length > 0 && <div className="search-dropdown">{searchResults.slice(0, 6).map(movie => <button type="button" className="search-item" key={movie.movie_id} onClick={() => openMovie(movie)}><span className="search-item-title">{displayTitle(movie.title)}</span><span className="search-item-genres">{movie.genres.join(' · ')}</span></button>)}<button type="button" className="search-item search-all" onClick={() => open('search')}>See all results</button></div>}</div><button type="button" className="user-widget" onClick={() => open('profile')}><div className="user-avatar">👤</div><div className="user-info"><strong>{entryMode === 'new' ? 'New CineMatch User' : `User ${selectedUser}`}</strong><small>Profile</small></div><span>▾</span></button></header>{error && <div className="status-banner offline">⚠ {error}<button type="button" onClick={() => setError('')}>Try Again</button></div>}<main className="content-area"><div className="page-heading"><span className="eyebrow">CINEMATCH / {view.replace('-', ' ')}</span><h1>{view === 'home' ? 'Your cinema, curated.' : view === 'movie' && selectedMovie ? displayTitle(selectedMovie.title) : view.replace('-', ' ')}</h1></div>{content}<footer className="app-footer">CineMatch · MovieLens collaborative filtering · SVD</footer></main></div></div>
}